### PR TITLE
Autotick update

### PR DESCRIPTION
**Pull request by anjos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #1, closes #2, closes #3, closes #4 and closes #6.

### CODE REVIEW

**Comment by anjos** [comment]
@conda-forge-admin, please restart ci

**Comment by anjos** [comment]
@conda-forge-admin, please restart ci

**Comment by wolfv** [comment]
@anjos can you add yourself as maintainer? Happy to merge then

**Comment by anjos** [comment]
> @anjos can you add yourself as maintainer? Happy to merge then

Sure, I shall - I thought this had to be a separate PR tho.  Let me push it.

**Pull request merged**
